# Data sources

- https://github.com/unitedstates/congress-legislators/
- https://github.com/thepanacealab/covid19_twitter
- https://ieee-dataport.org/open-access/coronavirus-covid-19-geo-tagged-tweets-dataset
- https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

## Congress Members Tweets
Since there are a lot of tweets and we don't have a developer account such that we could retrieve millions of tweets successfully, we opted to get the most basic information for each tweet. We retrieved the user's handle (i.e. username), the content of the tweet, geolocation data if any, the tweet id, and the language in which the tweet was written as determined by Twitter. If a language cannot be identified it is labeled as "und". This label is a bit misleading at times, but this issue is discussed further in the Missing Data section of this report. We limited our search to tweets from handles according to (this)[https://github.com/unitedstates/congress-legislators/] dataset of Twitter handles for each congress member. We also limited our search to tweets from 12:00 AM UTC 2020 to 11:59 PM UTC 2020. These seemed like reasonable bounds since COVID-19 was particularly virulent in the year 2020 and the vaccine was not widely available before 2021 either. There were other features we could get from Twitter such as an entities object and sentiment analysis. We felt that the utility of these sentiments was not worth the extra time it would take to retrieve and parse through those fields. Moreover, we can still choose  NLP models differing from those used by Twitter to extract information from tweet content. Thus extracting this information at the outset was not necessary, but comparing twitter sentiments and entities to those from other models could be useful in future work.

## Google's Changes in Mobility Data
There is not much we can change or alter about this dataset and it is quite robust. The gist of the dataset is that Google used it's geolocation data from its various users and services to determine relative changes in mobility between categories of places. These categories include: Retail & Recreation	Grocery & Pharmacy, Parks, Transit Stations, Workplaces, and Residential. Obviously, this is not a comprehensive list of all categories of places where people may congregate, but it is nonetheless a representative sample of places where we would expect a high volume of human traffic. Other places which are not included which could be useful to inquire about are large conventions. Even if they are less frequent, the high concentration of people and relative changes therein may have an outsized impact on COVID-19. This could be a useful follow-up to this project but separate data may need to be sourced or scraped from the web.

<!-- add df.head() for mobility data along with some summary statistics -->
## Number of tweets cases and mobility
The data sources we used for this part were the ecdc dataset about the COVID-19 cases and deaths during 2020 and the twitter data. In the first case, we filtered the table just to include the USA data, so that we could have a table diplaying date, number of cases, and deaths for each day. To better compare our data, we just focused on the prevaccine covid situation, starting from the 4/1/2020 till around 12/15/2020. For the twitter data, we had to webscrape the parts that we needed. The original dataset had the top 1000 bigrams in terms of occurrence for each day . To ease up our processes we decided to include only the top 50 most used covid-related bigrams.Furthermore, we also used the mobility data for general USA overview, that was webscraped previously.
