# Conclusion

In conclusion, even though we can find some correlation between the number of cases and the number of covid related tweets, it is hard to establish a possible causation. As we have seen, the correlation between tweets and cases is strong but, surprisingly negative. We may assert that even though Covid infected a lot of people,. with time people became accostumed to it on a social perspective. It was in one sense, 'normalized' so that is why the tweets related to covid kept going down even if the cases were exploding, (expecially in the last month). The number of deaths may appear not have a huge correlation on the number of tweets. For the mobility (we just saw retail movements), we did not find any great correlation with the number of cases by week. Nonetheless it seems that the related movement for retail activities is negatively correlated with the number of tweets, but we dont have a substantial correlation between number of cases and mobility. Perhaps changing the temporal interval could tell us more about this. A similar analysis could be done to the other cathegories of movement. So to our question 'can tweets be predictive of covid cases?' we may answer, 'yes but in an unexpected way'.

We can conclude that political differences are also clear when talking about covid-related tweets. Democrats are more concerned about the preventive measures, and they outline masks and social distancing as two separate ways to combat the virus. We can also see that republicans are more prone to talking about the lockdown, however sometimes it could be a way to criticise rather than promote. Using sentiment analysis we can see that  there is a clear negative sentiment of republicans towards a lockdown, whereas for democrats a lockdown is percepted more positive than other measures. 
