--- 
title: "US Congress - Tweets and COVID-19"
author: "Darvesh Gorhe, Thomas Holvoet, Nicolo Ricci"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
Data sources about COVID-19 abound and many have been visualized thoroughly. As such, to visually explore something new about COVID-19 is a challenge. However, a good place to start is by asking the question: what can we look at now that we couldn't look at previously in regards to COVID-19? That is to say, there is data which is retroactively useful to visualize that did not lend itself to daily, weekly, and monthly updates at the height of the pandemic. Some of these data sources are ones that have been used for those daily, weekly, and monthly updates. We do our best to augment those sources to provide new insights.

## Congress and Mobility
An interesting proxy that we have not found to be thoroughly studied is the relationship between public tweets by members of the United States Congress and mobility data. Pre-vaccine, mobility is a useful proxy for the spread of COVID-19 at least in a directional sense. Ignoring things like mask compliance, we can gain some coarse insights into the relationship of our constitutional representation and people's actual decision making. These insights can be determined through Google's publicly available changes in mobility datasets for each state and county therein. Since most congressional districts contain more than one county, we aggregate data by states rather than a per district level. We want to answer questions relating to the following: how do US Congress members' tweets correspond with changes in mobility? The null hypothesis in our case is that there is no relationship. The existence of a relationship would not necessarily imply a causal relationship. Nonetheless, it would be interesting to find two proxies for COVID-19 themselves having a relationship between one another.

The changes in mobility data are not very granular for privacy reasons, so we will primarily investigate different aspects of the tweets. The tweet content itself has an incredibly high dimensionality, but even features like the number of tweets will be useful to understand and "weight" relationships appropriately. Not all members of the US Congress tweet frequently, and some do not tweet at all. It could be the case that more tweets dilute the effect of any particular representative. On the other hand, members who tweet frequently might actually be more vocal and thereby more influential toward their constituents. This is just one example of how nuanced Twitter data can be. 

## Congress and Sentiment
A related concept is the sentiment of tweets from members of the US Congress. While the general public may have any amount of information from varying sources, US Congress members have access to confidential information which may, directly or indirectly, influence how they speak on public platforms like Twitter. We aim to look things adjacent to COVID-19 which may or may not be captured in the Congress and Mobility Section. We are classifying things with a coarse method even if it is considered state-of-the-art. Things like mask compliance, herd immunity, and social distancing are very obviously concepts related to COVID-19 but they may not be recognized as such when labeling with zero-shot classification.

